<a href="https://colab.research.google.com/github/mtazike/Applied-Database/blob/main/M1_Coding_Practice_Mahya_Tazike.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# M1 | Coding Practice – Database Overview
**Mahya Tazike**

---

## Table of Contents
1. [Import Libraries](#1.-Import-Libraries)
2. [Upload CSV Files](#2.-Upload-CSV-Files)
3. [Create SQLite Database](#3.-Create-SQLite-Database)
4. [Load CSV Data into Tables](#4.-Load-CSV-Data-into-Tables)
5. [SQL Queries (Chapter 1.1–1.5)](#5.-SQL-Queries-(Chapter-1.1–1.5))
   - [Problem 1.1 – Retrieving All Rows and Columns](#Problem-1.1-–-Retrieving-All-Rows-and-Columns)
   - [Problem 1.2 – Retrieving a Subset of Rows](#Problem-1.2-–-Retrieving-a-Subset-of-Rows)
   - [Problem 1.3 – Finding Rows That Satisfy Multiple Conditions](#Problem-1.3-–-Finding-Rows-That-Satisfy-Multiple-Conditions)
   - [Problem 1.4 – Retrieving a Subset of Columns](#Problem-1.4-–-Retrieving-a-Subset-of-Columns)
   - [Problem 1.5 – Providing Meaningful Names for Columns](#Problem-1.5-–-Providing-Meaningful-Names-for-Columns)
6. [Close Connection](#6.-Close-Connection)

## 1. Import Libraries
Import `sqlite3` for database connection and `pandas` for reading CSV files and displaying results.

In [ ]:
# Import libraries
import sqlite3  # SQLite database library
import pandas as pd  # Data handling and display

## 2. Mount Google Drive and Read CSV Files
Upload `emp.csv` and `dept.csv` into Google Colab.

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Read CSV files from Google Drive
emp_df = pd.read_csv("/content/drive/My Drive/Applied Database Technologies/emp.csv")
dept_df = pd.read_csv("/content/drive/My Drive/Applied Database Technologies/dept.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 3. Create SQLite Database
Create a new SQLite database and a cursor to execute SQL statements.

In [ ]:
# Connect to a new SQLite database
conn = sqlite3.connect("company.db")
cursor = conn.cursor()

## 4. Load CSV Data into Tables
Read the CSV files with `pandas` and load them into SQLite tables using `to_sql()`.

In [ ]:
# Load DataFrames into SQLite tables
emp_df.to_sql("emp", conn, if_exists="replace", index=False)
dept_df.to_sql("dept", conn, if_exists="replace", index=False)

print("Tables created and data loaded successfully.")

Tables created and data loaded successfully.

## 5. SQL Queries (Chapter 1.1–1.5)
Execute SQL queries from SQL Cookbook Chapter 1, Problems 1.1 through 1.5.

### Problem 1.1 – Retrieving All Rows and Columns
Use `SELECT *` to retrieve all data from the `emp` table.

In [ ]:
# Problem 1.1: Select all rows and columns
query_1 = """
SELECT *
FROM emp;
"""

pd.read_sql_query(query_1, conn)

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-Dec-05   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-Feb-06  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-Feb-06  1250   500.0      30
3    7566   JONES    MANAGER  7839.0   2-Apr-06  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-Sep-06  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0   1-May-06  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0   9-Jun-06  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0   9-Dec-07  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-Nov-06  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0   8-Sep-06  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  12-Jan-08  1100     NaN      20
11   7900   JAMES      CLERK  7698.0   3-Dec-06   950     NaN      30
12   7902    FORD    ANALYST  7566.0   3-Dec-06  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-Jan-07  1300     NaN      10

### Problem 1.2 – Retrieving a Subset of Rows
Use the `WHERE` clause to retrieve only employees in department 10.

In [ ]:
# Problem 1.2: Filter rows using WHERE
query_2 = """
SELECT *
FROM emp
WHERE deptno = 10;
"""

pd.read_sql_query(query_2, conn)

   EMPNO   ENAME        JOB     MGR   HIREDATE   SAL  COMM  DEPTNO
0   7782   CLARK    MANAGER  7839.0   9-Jun-06  2450  None      10
1   7839    KING  PRESIDENT     NaN  17-Nov-06  5000  None      10
2   7934  MILLER      CLERK  7782.0  23-Jan-07  1300  None      10

### Problem 1.3 – Finding Rows That Satisfy Multiple Conditions
Use `WHERE` with `AND` and `OR` to filter rows based on multiple conditions.

In [ ]:
# Problem 1.3: Multiple conditions with AND/OR
query_3 = """
SELECT *
FROM emp
WHERE deptno = 10
   OR comm IS NOT NULL
   OR sal <= 2000 AND deptno = 20;
"""

pd.read_sql_query(query_3, conn)

   EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0   7369   SMITH      CLERK  7902.0  17-Dec-05   800     NaN      20
1   7499   ALLEN   SALESMAN  7698.0  20-Feb-06  1600   300.0      30
2   7521    WARD   SALESMAN  7698.0  22-Feb-06  1250   500.0      30
3   7654  MARTIN   SALESMAN  7698.0  28-Sep-06  1250  1400.0      30
4   7782   CLARK    MANAGER  7839.0   9-Jun-06  2450     NaN      10
5   7839    KING  PRESIDENT     NaN  17-Nov-06  5000     NaN      10
6   7844  TURNER   SALESMAN  7698.0   8-Sep-06  1500     0.0      30
7   7876   ADAMS      CLERK  7788.0  12-Jan-08  1100     NaN      20
8   7934  MILLER      CLERK  7782.0  23-Jan-07  1300     NaN      10

### Problem 1.4 – Retrieving a Subset of Columns
Select only specific columns (`ename`, `deptno`, `sal`) instead of all columns.

In [ ]:
# Problem 1.4: Select specific columns
query_4 = """
SELECT ename, deptno, sal
FROM emp;
"""

pd.read_sql_query(query_4, conn)

     ENAME  DEPTNO   SAL
0    SMITH      20   800
1    ALLEN      30  1600
2     WARD      30  1250
3    JONES      20  2975
4   MARTIN      30  1250
5    BLAKE      30  2850
6    CLARK      10  2450
7    SCOTT      20  3000
8     KING      10  5000
9   TURNER      30  1500
10   ADAMS      20  1100
11   JAMES      30   950
12    FORD      20  3000
13  MILLER      10  1300

### Problem 1.5 – Providing Meaningful Names for Columns
Use `AS` to create readable column aliases for `sal` and `comm`.

In [ ]:
# Problem 1.5: Rename columns using aliases
query_5 = """
SELECT sal AS salary,
       comm AS commission
FROM emp;
"""

pd.read_sql_query(query_5, conn)

    salary  commission
0      800         NaN
1     1600       300.0
2     1250       500.0
3     2975         NaN
4     1250      1400.0
5     2850         NaN
6     2450         NaN
7     3000         NaN
8     5000         NaN
9     1500         0.0
10    1100         NaN
11     950         NaN
12    3000         NaN
13    1300         NaN

## 6. Close Connection
Close the SQLite database connection to free resources.

In [ ]:
# Close the database connection
conn.close()
print("Database connection closed.")

Database connection closed.